defaults:
  - _self_
  - database@_global_: island_small
  - evolution@_global_: small_budget
  - task@_global_: zork
  - cluster@_global_: local
  - variant@_global_: zork_8islands

verbose: false
results_dir: results
run_name: ${now:%Y.%m.%d}${now:%H%M%S}

output_dir: ${results_dir}/${exp_name}/${run_name}${variant_suffix}

hydra:
  run:
    dir: ${output_dir}
